### ISSUE TITLE
Case/control phenotypes to code 1/2 instead of 0/1

### ISSUE THREAD

**Issue by mboissel** [mcanouil/analysis-scripts-templates#3]
While testing this template I've had a message from plink2 telling the logistic regression wasn't performed because only controls were provided. It was in fact only a problem of phenotype coding. I suggest to check if the trait's values are all 0/1, if so, add +1 to recode them 1/2. 
Now it's working well in my application. 

https://github.com/mcanouil/analysis-scripts-templates/blob/aa0575ac7b5824235fd434918a55f70c7aec9dc4/R/functions/tar-gwas.R#L149-L153

 ```r
  if (model_type %in% "logistic" & all(c(0,1) %in% unique(dt[[ model[["raw_trait"]] ]]) )) {
    message("Case/control phenotypes are expected to be encoded as 1/2")
    # https://www.cog-genomics.org/plink/2.0/input#pheno
    # Case/control phenotypes are expected to be encoded as 1=unaffected (control), 2=affected (case)
    
    dt[[ model[["raw_trait"]] ]] <- as.numeric(as.character(dt[[ model[["raw_trait"]] ]])) + 1

  }
  data.table::fwrite(
    x = dt[j = .SD, .SDcols = c("#IID", model[["raw_trait"]])],
    file = sprintf("%s.pheno", basename_file),
    sep = " "
  )
```

**Comment by mcanouil** [comment]
Since it is documented in PLINK and reported by PLINK as well when the code is ran, I do not see any reason to add another layer of warnings on top of the warning/error message from PLINK.
